### ISSUE TITLE
I2C freezing on Arduino Zero

### ISSUE THREAD

**Issue by mbparks** [TEConnectivity/MS8607_Arduino_Library#1]
Not 100% sure why (yet) but it seems this library is causing the Arduino Zero to freeze. Works okay with the Arduino Uno.  Any thoughts as to why?

**Comment by williammarkezana** [comment]
Hi Mike,

After some investigations it seams to be caused by _Wire.begin()_ being called during the _MS8607_ class constructor which is, _on the provided example_, done before the board has completed its setup.
I added a _begin()_ function to the class so the Wire initialisation can be done properly.
Let me know if that fixes your issue.
